export const CONFIG = {
  BRAND_NAME: 'Quimica Clean',
  PRIMARY_COLOR: '#e7a73f',
  SECONDARY_COLOR: '#25D366',

  WHATSAPP_NUMBER: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || '+543813046228',

  SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,

  API_URL: process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000',
}
